### PR TITLE
mainthread: fix race condition in Call, CallErr and CallVal

### PR DESCRIPTION
**Pull request by mewmew**
Fixes faiface/pixel#68.

### CODE REVIEW

**Comment by faiface** [comment]
Ah, you're right, I realize the race condition now. How does this fix affect performance, though? If it does, maybe it would be appropriate to get the channels from pools?

**Comment by mewmew** [comment]
> Ah,  you're right, I realize the race condition now. How does this fix  affect performance, though? If it does, maybe it would be appropriate to  get the channels from pools?

Do you have any benchmark set up for pixel? If so, we could bench before and after. I'd rather wait with channel pools until it is confirmed that this is indeed a performance issue. Pre-mature optimization and all that..

**Comment by mewmew** [comment]
I've added a benchmark for the `mainthread` package. It is probably better to isolate the benchmark to the `mainthread` package, as Pixel could add a lot of noise.

If you think the degradation in performance is too much, feel free to take a stab at trying to improve the runtime numbers.

Cheers,
/u

**Comment by faiface** [comment]
Ok, I think this is good. If it causes any performance issues in the future, we'll deal with that.

Thanks a lot for the good job!

**Comment by mewmew** [comment]
Happy to see this merged. Have been playing with Pixel this weekend, and had a lot of fun! Wish you a great week!

Cheers,
/u

**Comment by faiface** [comment]
Feel free to share your creations if you like to :). (For example, on Gitter.) I always love to see new things created with Pixel.

**Pull request merged**
